apiVersion: v1
kind: Namespace
metadata:
  name: puppet
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: puppetserver
  namespace: puppet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: puppetserver
  template:
    metadata:
      labels:
        app: puppetserver
    spec:
      containers:
        - name: puppetserver
          image: ghcr.io/openvoxproject/openvoxserver:latest
          env:
          - name: OPENVOXSERVER_HOSTNAME
            value: puppet
          - name: USE_OPENVOXDB
            value: "false"
          ports:
          - containerPort: 8140
            name: https
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: puppet
  namespace: puppet
spec:
  ports:
    - name: https
      protocol: TCP
      port: 8140
  selector:
    app: puppetserver
