---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wazuh
  namespace: wazuh
spec:
  chartRef:
    kind: OCIRepository
    name: wazuh
    namespace: wazuh
  driftDetection:
    mode: enabled
  install:
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 3
  interval: 10m
  releaseName: wazuh
  test:
    enable: true
  timeout: 5m
  upgrade:
    remediation:
      retries: 3
  values:
