---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: wazuh
  namespace: wazuh
spec:
  interval: 5m0s
  provider: generic
  insecure: true
  ref:
    tag: 0.1.1
  timeout: 60s
  url: oci://zot.zot:5000/charts/wazuh
