---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: default
spec:
  targetNamespace: metallb-system
  storageNamespace: metallb-system
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: metallb
      version: 0.14.9
      sourceRef:
        kind: HelmRepository
        name: metallb
      interval: 5m
  releaseName: metallb
  install:
    createNamespace: true
    remediation:
      retries: -1
    crds: CreateReplace
  upgrade:
    remediation:
      retries: -1
    crds: CreateReplace
  test:
    enable: false
  driftDetection:
    mode: enabled
  values:
