{{- if .Values.keycloak.enabled }}
{{- $fullName := .Values.keycloak.name | default (include "keycloak-operator.fullname" .) -}}
{{ range .Values.keycloak.realmRoles }}
---
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmRole
metadata:
  name: {{ $fullName }}-{{ .name }}
spec:
  description: {{ .description }}
  name: {{ .name }}
  realmRef:
    name: {{ .realmName }}
    kind: KeycloakRealm
  {{ if .additionalSpec }}
  {{- toYaml .additionalSpec | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
