---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 1m
  timeout: 10m
  chart:
    spec:
      chart: gitlab
      version: 8.11.1
      sourceRef:
        kind: HelmRepository
        name: gitlab
      interval: 5m
  releaseName: gitlab
  install:
    createNamespace: true
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    remediation:
      retries: 3
    crds: CreateReplace
  test:
    enable: false
  driftDetection:
    mode: enabled
  values:
    gitlabUrl: https://gitlab.kind/
    global:
      hosts:
        domain: kind
        # gitlab:
          # hostnameOverride: gitlab.kind
      ingress:
        enabled: true
        configureCertmanager: false
        provider: cilium
        class: cilium
      kas:
        enabled: false
      minio:
        enabled: false
      registry:
        enabled: false
      appConfig:
        object_store:
          enabled: false
        lfs:
          enabled: false
        packages:
          enabled: false
        uploads:
          enabled: false
        artifacts:
          enabled: false
    certmanager:
      installCRDs: false
      nameOverride: certmanager
      install: false
      rbac:
        create: false
    nginx-ingress:
      enabled: false
    certmanager-issuer:
      email: email@example.com
    gitlab-runner:
      # gitlabUrl: https://gitlab.kind/
      runners:
        config: |
          [[runners]]
            url = "https://gitlab.kind"
            clone_url = "https://gitlab.kind"
            environment = ["GIT_SSL_NO_VERIFY=true"]
            [runners.kubernetes]
            image = "ubuntu:22.04"
              [[runners.kubernetes.host_aliases]]
                "ip" = "172.18.0.6"
                "hostnames" = ["gitlab.kind"]
              [[runners.kubernetes.host_aliases]]
                "ip" = "172.18.0.6"
                "hostnames" = ["vault.kind"]
            [[runners.kubernetes.volumes.secret]]
              name = "gitlab-wildcard-tls-ca"
              mount_path = "/etc/gitlab-runner/certs/"
              read_only = true

      install: true
      volumes:
        - name: gitlab-wildcard-tls-ca
          secret:
            defaultMode: 420
            secretName: gitlab-wildcard-tls-ca
      volumeMounts:
        - mountPath: /etc/ssl/certs/gitlab-ca.pem
          name: gitlab-wildcard-tls-ca
          subPath: cfssl_ca
      hostAliases:
      - ip: "172.18.0.6"
        hostnames:
        - "gitlab.kind"
      - ip: "172.18.0.6"
        hostnames:
        - "vault.kind"
    prometheus:
      install: false
    redis:
      install: true
    gitlab:
      toolbox:
        enabled: false
      gitlab-shell:
        enabled: false
      webservice:
        minReplicas: 1
        workerProcesses: 1
        puma:
          threads:
            min: 1
            max: 1
          workerMaxMemory: 1024 # in MB units
    registry:
      enabled: false
