---
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: cluster
  namespace: default
spec:
  controlPlane:
    machineHealthCheck:
      unhealthyConditions:
        - status: Unknown
          timeout: 300s
          type: Ready
        - status: 'False'
          timeout: 300s
          type: Ready
    machineInfrastructure:
      ref:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OpenStackMachineTemplate
        name: control-plane
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KubeadmControlPlaneTemplate
      name: control-plane
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: OpenStackClusterTemplate
      name: cluster
  patches: []
  workers:
    machineDeployments:
      - class: default-worker
        machineHealthCheck:
          unhealthyConditions:
            - status: Unknown
              timeout: 300s
              type: Ready
            - status: 'False'
              timeout: 300s
              type: Ready
        template:
          bootstrap:
            ref:
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
              kind: KubeadmConfigTemplate
              name: default-worker-bootstraptemplate
          infrastructure:
            ref:
              apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
              kind: OpenStackMachineTemplate
              name: default-worker-machinetemplate
