---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: default-worker-machinetemplate
  namespace: default
spec:
  template:
    spec:
      sshKeyName: makar
      flavor: SL1.2-4096-32
      image:
        filter:
          name: kube-v1.32.2
