{{- if .Values.keycloak.ingress.external.enabled -}}
{{- $fullName := .Values.keycloak.name | default (include "keycloak-operator.fullname" .) -}}
{{- $svcPort := .Values.keycloak.http.httpPort | default "8080" -}}
{{- if and .Values.keycloak.ingress.external.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.keycloak.ingress.external.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.keycloak.ingress.external.annotations "kubernetes.io/ingress.class" .Values.keycloak.ingress.external.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
  {{- with .Values.keycloak.ingress.external.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.keycloak.ingress.external.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.keycloak.ingress.external.className }}
  {{- end }}
  {{- if .Values.keycloak.ingress.external.tls }}
  tls:
    {{- range .Values.keycloak.ingress.external.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.keycloak.hostname.hostname }}
      http:
        paths:
          - path: "/"
            pathType: "Prefix"
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-service
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}-service
              servicePort: {{ $svcPort }}
              {{- end }}
{{- end }}
