{{- $fullName := .Values.keycloak.name | default (include "keycloak-operator.fullname" .) -}}
{{ if .Values.keycloak.genPass }}
---
{{- $secret_name := printf "%s-initial-admin" $fullName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-initial-admin
data:
  username: YWRtaW4=
  {{- $old_sec := lookup "v1" "Secret" $.Release.Namespace $secret_name }}
  {{- if or (not $old_sec) (not $old_sec.data) }}
  password: {{ randAlphaNum 20 | b64enc }}
  {{ else }}
  password: {{ index $old_sec.data "password" }}
  {{- end }}
{{ end }}
