---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  kubeConfig:
    secretRef:
      name: tenant2-cluster-kubeconfig
  values:
    k8sServiceHost: auto
    cluster:
      name: tenant1-cluster
      id: 1
    rollOutCiliumPods: false
    operator:
      enabled: true
    bandwidthManager:
      enabled: false
      bbr: false
    envoy:
      enabled: true
    bpf:
      masquerade: true
    kubeProxyReplacement: true
    gatewayAPI:
      enabled: false
      secretsNamespace:
        enabled: false
    hostFirewall:
      enabled: true
    hostPort:
      enabled: true
    socketLB:
      enabled: true
      hostNamespaceOnly: true
    nodePort:
      enabled: true
      enableHealthCheck: true
      enableHealthCheckLoadBalancerIP: true
    externalIPs:
      enabled: true
    ingressController:
      enabled: false
      default: true
      secretsNamespace:
        create: true
    bgpControlPlane:
      enabled: true
      secretsNamespace:
        create: false
    egressGateway:
      enabled: false
    hubble:
      enabled: true
      ui:
        enabled: false
      metrics:
        enableOpenMetrics: true
        enabled:
          - dns
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - httpV2:exemplars=true
    localRedirectPolicy: false
    ipam:
      mode: cluster-pool
      operator:
        clusterPoolIPv4PodCIDRList: 10.244.0.0/16
    enableInternalTrafficPolicy: true
    enableLBIPAM: true
# TODO: pay attention to newlines at the end that get inserted by templates
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: occm
spec:
  kubeConfig:
    secretRef:
      name: tenant2-cluster-kubeconfig
  values:
    secret:
      enabled: true
      create: false
      name: tenant2-cloudconf
