---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak-stack
  namespace: keycloak-stack
spec:
  interval: 10m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: keycloak-stack
    namespace: keycloak-stack
  releaseName: keycloak-stack
  install:
    createNamespace: true
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    remediation:
      retries: 3
    crds: CreateReplace
  test:
    enable: true
  driftDetection:
    mode: enabled
  values:
    keycloak-configure:
      keycloak:
        name: keycloak
        hostname:
          hostname: keycloak-service:8080
          schema: http
        enabled: true
        realms:
          - name: realm01
            realmName: realm01
    keycloak-operator:
      keycloak:
        enabled: true
        genPass: true
        name: keycloak
        hostname:
          backchannelDynamic: true
          hostname: http://keycloak.localhost
          strict: false
        proxy:
          headers: xforwarded
        db:
          create: true
          database: keycloak-pgdb01-cluster-user
          host: keycloak-pgdb01-cluster-rw
          port: 5432
          passwordSecret:
            name: keycloak-pgdb01-cluster-app
            key: password
          usernameSecret:
            name: keycloak-pgdb01-cluster-app
            key: username
          vendor: postgres
        ingress:
          enabled: true
          external:
            enabled: false
            annotations: {}
            className: "cilium"
            hosts:
              - host: keycloak.localhost
            # tls:
            #   - hosts:
            #       - keycloak.localhost
            #     secretName: keycloak.example.com
        unsupported:
          podTemplate:
            spec:
              containers:
                - name: keycloak
                  securityContext:
                    allowPrivilegeEscalation: false
                    capabilities:
                      drop:
                        - ALL
                    privileged: false
                    readOnlyRootFilesystem: false
                    runAsNonRoot: true
                    seccompProfile:
                      type: RuntimeDefault
              securityContext:
                fsGroup: 1000
                runAsGroup: 1000
                runAsNonRoot: true
                runAsUser: 1000
                seccompProfile:
                  type: RuntimeDefault
      imagePullSecrets: []
      nameOverride: ""
      fullnameOverride: ""
      operator:
        enabled: true
        replicaCount: 1
        image:
          pullPolicy: IfNotPresent
          tag: "25.0.2"
        config:
          keycloakImage:
            tag: "25.0.2"
        serviceAccount:
          create: true
        podSecurityContext:
          fsGroup: 2000
        securityContext:
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          runAsNonRoot: true
          runAsUser: 1000
        service:
          enabled: true
          type: ClusterIP
          port: 8080
    keycloak-operator-configurator:
      clusterReconciliationEnabled: false
      name: keycloak-operator-configurator
    cluster:
      fullnameOverride: keycloak-pgdb01-cluster
      mode: standalone
      cluster:
        monitoring:
          enabled: true
          podMonitor:
            enabled: true
          prometheusRule:
            enabled: false
        affinity:
          enablePodAntiAffinity: true
          podAntiAffinityType: preferred
          topologyKey: kubernetes.io/hostname
        initdb:
          database: keycloak-pgdb01-cluster-user
          encoding: UTF8
          localeCType: en_US.UTF8
          localeCollate: en_US.UTF8
          owner: keycloak-pgdb01-cluster-user
        instances: 1
        primaryUpdateMethod: switchover
        primaryUpdateStrategy: unsupervised
        resources:
          limits:
            cpu: "2"
            memory: 2048Mi
          requests:
            cpu: 200m
            memory: 1024Mi
        storage:
          resizeInUseVolumes: true
          size: 25Gi
          storageClass: "standard"
        enableSuperuserAccess: false
      backups:
        enabled: false
        endpointCA:
          create: false
