---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: keycloak-stack
  namespace: keycloak-stack
spec:
  interval: 5m0s
  provider: generic
  ref:
    tag: 0.1.2
  timeout: 60s
  insecure: true
  url: oci://zot.zot:5000/charts/keycloak-stack
