---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tenant1
resources:
  - ../../../packages/apps/cilium
  - ./cluster
  - ./namespace.yaml
transformers: [./prefixtransformer.yaml]
patches:
  - path: ./patch.yaml
