---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  values:
    additionalEnv:
      - name: OIDC_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: keycloak-vault-oauth-key
            key: key
    vault:
      podSpec:
        hostAliases:
        - ip: "172.18.0.8"
          hostnames:
          - "keycloak.localhost"
        - ip: "172.18.0.7"
          hostnames:
          - "keycloak.localhost"
        - ip: "172.18.0.6"
          hostnames:
          - "keycloak.localhost"
        - ip: "172.18.0.5"
          hostnames:
          - "keycloak.localhost"
        - ip: "172.18.0.8"
          hostnames:
          - "gitlab.kind"
        - ip: "172.18.0.7"
          hostnames:
          - "gitlab.kind"
        - ip: "172.18.0.6"
          hostnames:
          - "gitlab.kind"
        - ip: "172.18.0.5"
          hostnames:
          - "gitlab.kind"
      externalConfig:
        policies:
          - name: allow_namespaced_secrets
            rules: |
              path "namespaces/data/{{identity.entity.aliases.${ accessor `kubernetes/` }.metadata.service_account_namespace}}/*" {
                capabilities = ["create", "read", "update", "delete", "list"]
              }
          - name: allow_namespaced_secrets
            rules: |
              path "namespaces/data/{{identity.entity.aliases.${ accessor `kubernetes/` }.metadata.service_account_namespace}}/*" {
                capabilities = ["create", "read", "update", "delete", "list"]
              }
          - name: allow_shared_secrets
            rules: |
              path "shared/*" {
                capabilities = ["create", "read", "update", "delete", "list"]
              }
          - name: allow_admin
            rules: |
              path "*" {
                capabilities = ["create", "read", "update", "delete", "list", "sudo"]
              }
          - name: allow_viewer
            rules: |
              path "*" {
                capabilities = ["read", "update", "list"]
              }
        auth:
          - type: jwt
            path: jwt
            config:
              oidc_discovery_url: https://gitlab.kind
              bound_issuer: https://gitlab.kind
            roles:
            - name: default
              bound_audiences:
                - https://vault.kind
              user_claim: user_email
              policies: allow_shared_secrets
              token_explicit_max_ttl: 60
              bound_claims_type: "glob"
              bound_claims: {
                "project_id": "*",
                "ref": "*"
              }
            
          - type: kubernetes
            roles:
              # Allow every pod in the default namespace to use the secret kv store
              - name: default
                bound_service_account_names: ["default"]
                bound_service_account_namespaces: ["*"]
                policies: ["allow_shared_secrets", "allow_namespaced_secrets"]
                ttl: 1h
          - type: oidc
            config:
              oidc_discovery_url: "http://keycloak.localhost/realms/realm01"
              oidc_client_id: vault-oauth
              oidc_client_secret: "${ env `OIDC_CLIENT_SECRET` }"
              default_role: default
            roles:
              # Allow every pod in the default namespace to use the secret kv store
              - name: default
                allowed_redirect_uris: ["https://vault.kind/ui/vault/auth/oidc/oidc/callback","https://vault.kind/oidc/callback","https://vault.kind:/oidc/callback","https://vault.kind:443/oidc/callback","http://localhost:8250/oidc/callback"]
                bound_audiences: vault-oauth
                user_claim: preferred_username
                groups_claim: "groups"
              - name: admin
                allowed_redirect_uris: ["https://vault.kind/ui/vault/auth/oidc/oidc/callback","https://vault.kind/oidc/callback","https://vault.kind:/oidc/callback","https://vault.kind:443/oidc/callback","http://localhost:8250/oidc/callback"]
                bound_audiences: vault-oauth
                user_claim: preferred_username
                policies: allow_admin
                bound_claims:
                  groups: 
                    - admin
