---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: vault
  namespace: vault
spec:
  interval: 5m0s
  provider: generic
  ref:
    tag: 0.30.0
  timeout: 60s
  insecure: true
  url: oci://zot.zot:5000/charts/vault
