---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: open-telemetry
  namespace: opentelemetry
spec:
  interval: 5m
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
