---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-kube-stack
  namespace: opentelemetry
spec:
  targetNamespace: opentelemetry
  storageNamespace: opentelemetry
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: opentelemetry-kube-stack
      version: 0.4.5
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
      interval: 5m
  releaseName: otel
  install:
    createNamespace: true
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    remediation:
      retries: 3
    crds: CreateReplace
  test:
    enable: false
  driftDetection:
    mode: enabled
  values:
    clusterRole:
      enabled: true
    opentelemetry-operator:
      replicaCount: 1
      manager:
        collectorImage:
          repository: otel/opentelemetry-collector-k8s
        serviceAccount:
          create: true
        serviceMonitor:
          enabled: true
        prometheusRule:
          enabled: false
          defaultRules:
            enabled: true
        createRbacPermissions: false
        leaderElection:
          enabled: true
        rolling: false
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      kubeRBACProxy:
        enabled: true
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      securityContext:
        runAsGroup: 65532
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 65532
        fsGroup: 65532
    defaultCRConfig:
      enabled: true
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop: [ALL]
      podSecurityContext:
        runAsUser: 1001
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    collectors:
      daemon:
        enabled: false
      cluster:
        enabled: false
