---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trust-manager
  namespace: trust-manager
spec:
  interval: 1m
  timeout: 10m
  chart:
    spec:
      chart: trust-manager
      version: 0.16.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
      interval: 5m
  releaseName: trust-manager
  install:
    remediation:
      retries: 10
    crds: CreateReplace
  upgrade:
    remediation:
      retries: 3
    crds: CreateReplace
  test:
    enable: true
  driftDetection:
    mode: enabled
  values:
    secretTargets:
      enabled: true
      authorizedSecrets:
        - ca.bundle.pem
