---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: grafana-operator
  namespace: grafana-operator
spec:
  interval: 5m0s
  provider: generic
  ref:
    tag: v5.17.0
  timeout: 60s
  url: oci://ghcr.io/grafana/helm-charts/grafana-operator
